// <auto-generated />
namespace Vidly.Migrations
{
    using System.CodeDom.Compiler;
    using System.Data.Entity.Migrations;
    using System.Data.Entity.Migrations.Infrastructure;
    using System.Resources;
    
    [GeneratedCode("EntityFramework.Migrations", "6.4.4")]
    public sealed partial class AddPropToMovie : IMigrationMetadata
    {
        private readonly ResourceManager Resources = new ResourceManager(typeof(AddPropToMovie));
        
        string IMigrationMetadata.Id
        {
            get { return "202008301547131_AddPropToMovie"; }
        }
        
        string IMigrationMetadata.Source
        {
            get { return null; }
        }
        
        string IMigrationMetadata.Target
        {
            get { return Resources.GetString("Target"); }
        }
    }
}
